### ISSUE TITLE
Cannot stop Windows Service

### ISSUE THREAD

**Issue by jachin84** [mmbot/mmbot#203]
I've installed mmbot as a Windows service but when attempting to stop the service I receive the message:

`Error 1061: The service cannot accept control messages at this time.`

**Comment by PeteGoo** [comment]
Is there anything else in the event log?

Does it start directly from a command prompt?

**Comment by jachin84** [comment]
Sorry I should have checked. The event log has an error:
```
Failed to stop service. System.Runtime.Remoting.RemotingException: Object '/3c782d23_223e_4d55_9b33_c7177775871b/kvkpjymornpcwnlxixqnqj6u_3.rem' has been disconnected or does not exist at the server.
   at mmbot.RobotWrapper.Stop()
   at mmbot.RobotRunner.Stop() in c:\Data\Source\mmbot\mmbot\RobotRunner.cs:line 35
   at mmbot.Service.OnStop() in c:\Data\Source\mmbot\mmbot\Service.cs:line 42
   at System.ServiceProcess.ServiceBase.DeferredStop()```

I've not had any issues running it via the command line yet.

**Comment by jjnsx29** [comment]
I'm seeing this exact issue as well when running mmbot as a Windows service. Also, not sure it is related, but after a few hours it seems to "hang" and not receive any more messages (using HipChatAdapter). Since I can't stop/restart the service, I have to use Task Manager to kill the process and manually start it up again.
